const container = document.querySelector('.container')

const div1 = document.createElement('div')
container.appendChild(div1)
const div2 = document.createElement('div')
container.appendChild(div2)
const div3 = document.createElement('div')
container.appendChild(div3)
const div4 = document.createElement('div')
container.appendChild(div4)
const div5 = document.createElement('div')
container.appendChild(div5)
const div6 = document.createElement('div')
container.appendChild(div6)
const div7 = document.createElement('div')
container.appendChild(div7)
const div8 = document.createElement('div')
container.appendChild(div8)
const div9 = document.createElement('div')
container.appendChild(div9)
const div10 = document.createElement('div')
container.appendChild(div10)
const div11 = document.createElement('div')
container.appendChild(div11)
const div12 = document.createElement('div')
container.appendChild(div12)
const div13 = document.createElement('div')
container.appendChild(div13)
const div14 = document.createElement('div')
container.appendChild(div14)
const div15 = document.createElement('div')
container.appendChild(div15)
const div16 = document.createElement('div')
container.appendChild(div16)




